# Site settings
title: 20th Workshop on Workflows in Support of Large-Scale Science
acronym: WORKS 2025

google_analytics: UA-18066333-14

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
  - jekyll-feed       # Adds feed to the website at /feed.xml
  - jekyll-seo-tag    # Adds all the important SEO meta tags by default.

exclude:
  - .jekyll-cache
  - README.md
  - LICENSE
