# Site settings
title: WORKS Workshop
avatar: assets/images/works-logo-dark-2021.png
google_analytics: UA-18066333-14

# Build settings
markdown: kramdown

#theme: jekyll-theme-prologue
collections: [sections]
